name: persistent_bottom_nav_bar
description: A persistent bottom navigation bar for flutter. It includes a total of 8 styles in addition to platform specific and bottom nav bar visibility settings.

homepage: https://github.com/BilalShahid13/PersistentBottomNavBar
repository: https://github.com/BilalShahid13/PersistentBottomNavBar
version: 0.0.5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_device_type: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
