name: persistent_bottom_nav_bar
description: A feature rich persistent bottom navigation bar for flutter

homepage: https://github.com/BilalShahid13/PersistentBottomNavBar
respository: https://github.com/BilalShahid13/PersistentBottomNavBar
version: 0.0.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_device_type: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
